---
server:
  port: 8080
virtualhosts:
  - host: localhost
    aliases:
      - ser1
      - s1
    routes:
      - pattern: /hi
        pass: http://localhost:8081/hi
      - pattern: ^/bye/*
        pass: http://localhost:8081/bye
  - host: service2
    aliases:
      - ser2
      - s2
